### ISSUE TITLE
Service 'ssh-server' failed to build

### ISSUE THREAD

**Issue by rkdasari** [Simon-Initiative/authoring-dev#22] opened 2019-05-10 05:38 UTC
I tried to overcome this error but could not. Could you let me know where the issue might be? Thank you

![nobasicauth](https://user-images.githubusercontent.com/5461520/57504844-1d2aa000-72c4-11e9-88c8-2b4c48bfd163.png)

**Comment by darrensiegel** [comment] 2019-05-10 11:59
First, thanks for filing this issue. 

I believe the root cause is that we are still hosting that docker image on our private, local docker repository.  We need to transition this to the public docker registry.

**Comment by darrensiegel** [comment] 2019-05-10 18:13
We've just landed a fix to master that (amongst some other cleanup changes) removes the ssh-server container from the development environment altogether.  This ssh-server container is really only necessary in production environments.

**Closed by darrensiegel** 2019-05-10 18:13 UTC
